### PR TITLE
Bug fixes

### LINKED ISSUE #262: The elapsed time meter shows wrong data
I've made a [post](https://steemit.com/stemms/@tibonova/pierce-the-butter-1485035761-9213154). Checked it on my Busy [profile page](https://app.busy.org/@tibonova), and it showed I've submitted it an hour ago. That was not true (maybe half an hour old post), but I thought it was just rounding. However, I refreshed the page and it showed "2 hours ago" immediately. 
It shows that time now, also after more refreshes. 

Busy post time

This is impossible, since as I'm writing this, steemd.com [shows](https://steemd.com/stemms/@tibonova/pierce-the-butter-1485035761-9213154) "55 minutes ago" (and that's right).

### LINKED ISSUE #298: Delete key is not appropriately functional
Using Chrome on Windows 10. Delete key does not work often in the editor.

### LINKED ISSUE #345: Missing spell checker in post editor
#### Expected behavior

When I write a post elsewhere, I could fix a lot of typos with the help of the spell checker. Missing it is a reason to write my posts outside Busy (_Draft_ looses from it's value). 

#### Actual behavior

There is no option to use a spell checker.

#### How to reproduce

1. Start a new post 
1. Write `asdasdasd` in that
1. Smile a bit during the hard work :smiley: _(optional)_
1. Check that if it is underlined  (it should)

* Browser: Firefox 51.0.1 & Chromium Version 55.0.2883.87
* Operating system: Ubuntu 16.10 (64bit) 

<sup>PS.: I like this template better, it's less redundant.</sup>

### LINKED ISSUE #371: Code not embedded properly
screen shot 2017-02-13 at 18 15 14

### LINKED ISSUE #427: Spellcheck not working everywhere
#### Expected behavior

I want a spellcheck when writing a new post.

#### Actual behavior

Spellcheck work on comment but not fully on /write page editor. On Chrome it would not work for content body. In Firefox it would not work for title, content and tags.

#### How to reproduce

Go to busy.org/write and write new post.

Browser: Chrome & Firefox

### PR DESCRIPTION
**Pull request by nil1511**
Fix #262 
Fix #371 
Fix #298 
Fix #427 
Fix #345

### CODE REVIEW

**Comment by nil1511** [comment]
@adcpm It should work fine now.

File: src/helpers/steemitHtmlReady.js [hunk 1]
```diff
@@ -241,6 +244,25 @@ function linkify(content, mutate, hashtags, usertags, images, links) {
   return content;
 }
 
+function embedable(child, links, images) {
```
Comment (p0o) [inline src/helpers/steemitHtmlReady.js]: Boolean functions better to start with is like `isEmbedable()` also it's better to explain the process in a comment since the function is a little unclear.

File: src/post/BodyShort.js [hunk 2]
```diff
@@ -13,9 +13,8 @@ module.exports = React.createClass({
     this.setState({ seeMore: true });
   },
   render() {
-    let body = striptags(remarkable.render(this.props.body));
+    let body = striptags(remarkable.render(this.props.body.replace(/&lt;/g, '<').replace(/&gt;/g, '>')));
```
Comment (p0o) [inline src/post/BodyShort.js]: please put the regex in a getter function with a self explanatory name and then pass it to remarkable. No need to put it in a separate helper file if it's only used here.

**Comment by nil1511** [comment]
@p0o Can you check now?
